Skip to content
Your account has been flagged.
Because of that, your profile is hidden from the public. If you believe this is a mistake, contact support to have your account status reviewed.

cryptobot
Repositories370
Code2K
Commits375
Issues89
Marketplace0
Topics1
Wikis7
Users24
Languages
123 Python
70 JavaScript
21 C#
18 Java
18 PHP
6 HTML
6 TypeScript
5 Go
4 Jupyter Notebook
4 Ruby
Advanced search 
370 repository results
AdeelMufti/CryptoBot
High(ish) frequency trading bot for cryptocurrencies, using Machine Learning for future price predictions
Apache-2.0 license

Updated 4 days ago

 Python
 175
IIIIIHIIIII/WhatBot
Whatsapp CryptoBot.
GPL-3.0 license

Updated on Aug 9, 2015

 Python
 10
OFRBG/TsukiBot
Discord CryptoBot for Spot Prices (and more)
discord-bot
bot
cryptocurrency
trade
discordbots
MIT license

Updated on Jan 8

 JavaScript
 29
EFForg/cryptobot-email
AGPL-3.0 license

Updated on May 22, 2014

 Python
 62
LaBaleineFr/LaBaleineDeWallStreet
CryptoBot - Discord - Price - Conv - Chart
Updated on Jan 31, 2018

 Python
 8
alfredholmes/cryptobot
A bot to manage nicehash mining
MIT license

Updated on Mar 31, 2017

 Python
 9
bibz0r/cryptoBot
A simple conditional PHP-based altcoin trading bot for the bittrex exchange
MIT license

Updated on Oct 31, 2018

 PHP
 11
meme-lord/CryptoBot
A cryptocurrency Discord chat bot
Updated on Jul 31, 2018

 JavaScript
 8
Herklos-Bots/CryptoBot_OLD Archived
CryptoBot is a simple trading bot using telegram channel signals
telegram
python
trading-bot
cryptocurrency
Apache-2.0 license

Updated on Jun 11, 2018

 Python
 18
Zane-/cryptobot
Tools for creating cryptocurrency trading bots using the unified CCXT library
Updated on Mar 22, 2018

 Python
 6
© 2019 GitHub, Inc.
Terms
Privacy
Security
Status
Help
Contact GitHub
Pricing
API
Training
Blog
About
Press h to open a hovercard with more details.
